### ISSUE TITLE
Please help, I have problems

### ISSUE THREAD

**Issue by ShankoAndrei** [rcs333/VAPiD#13]
Hi everyone,
Hope you'll help me. I uploaded VAPiD and all necessary modules. Unfortunately, I couldn't start. 

Here, the result with my own files. 
PS C:\Users\shank\PycharmProjects\BioPython_Tree\VAPiD> python vapid.py C:\Users\shank\PycharmProjects\BioPython_Tree\BioPython_Tree\data\Measles_FORT_L16.fasta ### fasta file
C:\Users\shank\PycharmProjects\BioPython_Tree\BioPython_Tree\data\Measles_FORT-L16.sbt ### sbt file 
--metadata_loc C:\Users\shank\PycharmProjects\BioPython_Tree\BioPython_Tree\data\Measles_FORT_L16.csv ### metadata file
--online ### because local DB doesn't work

**metadata not found in provided .csv or .csv not created** -  time for minimal manual entry for sequence - Measles_FORT_L16
Traceback (most recent call last):
  File "C:\Users\shank\PycharmProjects\BioPython_Tree\VAPiD\vapid.py", line 958, in <module>
    metadata, coverage, full_name_list[x] = do_meta_data(virus_strain_list[x], True, full_name_list[x])
  File "C:\Users\shank\PycharmProjects\BioPython_Tree\VAPiD\vapid.py", line 863, in do_meta_data
    col = ' [collection-date=' + raw_input('Enter collection date in the format (23-Mar-2005, Mar-2005, or 2005): ').strip() + ']'
NameError: **name 'raw_input' is not defined** 

Why there is no metadata in my csv file? Somebody, say something!
Regards, Andrei

**Comment by gamlopez** [comment]
I have the same problem. Please, could the authors answer the question.

**Comment by ShankoAndrei** [comment]
It's frustrating no one could help. I wonder if the project has already been abandoned. Is there anybody who uses VAPiD? Please, a little help would be good.

**Comment by rcs333** [comment]
Hi Andrei,

I'm in medical school so I don't check this repository very often. That being said this looks like an easy fix. 

Try using 
`python vapid3.py example.fasta example.sbt --metadata_loc example_metadata.csv`

I need to go through and make the documentation more clear but I have two versions of the programs vapid.py and vapid3.py

vapid.py is the original version which was developed on python 2.7.14 I've kept it in the repository because some of my users are still using python 2.7.14. 

This error occurs when you run the python 2.7.14 code with python 3+.

To fix try using vapid3.py. You can use all the same arguments and everything. 

Please let me know if this fixes your problem! I'm always happy to help out when I have the time. 

Ryan

**Comment by ShankoAndrei** [comment]
Hi Ryan,
Thank you very much, I should have guessed about it!))
