### ISSUE TITLE
running VAPiD throws IndexError: list index out of range

### ISSUE THREAD

**Issue by anajung** [rcs333/VAPiD#14]
Hi Ryan, 

**I ran the command below**
`python3 vapid3.py WUSTL_000226.consensus.fa template.sbt --spell_check --all`

**But it throws this Error:**
```
Searching local blast database at all_virus.fasta
Warning: [blastn] Examining 5 or more matches is recommended
KJ473815.1 was the selected reference
BtRs-BetaCoV/GX2013, was the parsed name of the virus
Aligning reference and query...
Traceback (most recent call last):
  File "vapid3.py", line 969, in <module>
    meta_list[x], coverage_list[x], sbt_file_loc, full_name_list[x],nuc_acid_type)
  File "vapid3.py", line 634, in annotate_a_virus
    name_of_virus, our_seq, ref_seq, ref_accession, need_to_rc = blast_n_stuff(strain, strain + SLASH + strain + '.fasta')
  File "vapid3.py", line 253, in blast_n_stuff
    if '_R_' in ali_list[1]:
IndexError: list index out of range
```

It would be great to receive assistance on this, thanks!
-Ana

**Comment by rcs333** [comment]
Hi Ana,

I think I've seen this one before but it has been a while. If it's not too much trouble can you upload the sequence you are trying to annotate and the version of vapid you are using? 

Ryan

**Comment by anajung** [comment]
Hi Ryan,

Thank you for the prompt reply. 
I am using vapid3.py v1.6.7.
Github does not seem to accept fasta format files so I am attaching it as a text file.

[WUSTL_000226_A131.consensus.fa.txt](https://github.com/rcs333/VAPiD/files/7961759/WUSTL_000226_A131.consensus.fa.txt)

Ana

**Comment by rcs333** [comment]
Okay I took a look at your sequence on my computer. 

The command 

`python3 vapid3.py WUSTL_000226_A131.fasta example.sbt --r MW938189.1`

Produces the error free and correctly annotated result I've attached. 
[WUSTL_000226_A131.gbf.txt](https://github.com/rcs333/VAPiD/files/7966307/WUSTL_000226_A131.gbf.txt)


The problem is almost certainly a missing dependency, and I'm pretty sure for you it's [maafft](https://mafft.cbrc.jp/alignment/software/). Please verify you are you able to run the example test files.

`python3 vapid3.py example.fasta example.sbt`

If you're sure you've got mafft correctly installed zip the entire output folder and send it to me.
