### ISSUE TITLE
VAPID run error

### ISSUE THREAD

**Issue by sekhwal** [rcs333/VAPiD#16]
Hi,
I have downloaded VAPiD-master folder and running VAPID with the following command, it shows following error. Please help me to figure out the error.

run command:
python /VAPiD-master/vapid.py --db all_virus.fasta rndm_assembly.fasta template.sbt
error:

metadata not found in provided .csv or .csv not created -  time for minimal manual entry for sequence - 1
Traceback (most recent call last):
  File "/VAPiD-master/vapid.py", line 958, in <module>
    metadata, coverage, full_name_list[x] = do_meta_data(virus_strain_list[x], True, full_name_list[x])
  File "/home/mmk6053/Bcov_new/rndm-reads/vapid_run/VAPiD-master/vapid.py", line 863, in do_meta_data
    col = ' [collection-date=' + raw_input('Enter collection date in the format (23-Mar-2005, Mar-2005, or 2005): ').strip() + ']'
NameError: name 'raw_input' is not defined

**Comment by rcs333** [comment]
Hi!

This is a problem running the python 2 version on python 3. Instead try `python vapid3.py ...` 

Hopefully this works for you and happy annotating!

Ryan

**Comment by sekhwal** [comment]
I am trying python vapid3.py. Also, I generated the index files of my genome fasta file using makeblastdb. However, it still showing following error. 

running command:

python /VAPiD-master/vapid3.py --db all_virus.fasta rndm_assembly.fasta template.sbt --metadata_loc metadata.csv

---
BLAST Database error: No alias or index file found for nucleotide database [all_virus.fasta] in search path [/Bcov_new/rndm-reads/vapid_run::]
Traceback (most recent call last):
  File "/VAPiD-master/vapid3.py", line 968, in <module>
    strain2species[virus_strain_list[x]] = annotate_a_virus(virus_strain_list[x], virus_genome_list[x],
  File "/VAPiD-master/vapid3.py", line 634, in annotate_a_virus
    name_of_virus, our_seq, ref_seq, ref_accession, need_to_rc = blast_n_stuff(strain, strain + SLASH + strain + '.fasta')
  File "/VAPiD-master/vapid3.py", line 186, in blast_n_stuff
    record = Entrez.read(Entrez.esearch(db='nucleotide', term=ref_seq_gb))
UnboundLocalError: local variable 'ref_seq_gb' referenced before assignment
