### ISSUE TITLE
UnboundLocalError: local variable 'ref_seq_gb' referenced before assignment

### ISSUE THREAD

**Issue by Cerebro409** [rcs333/VAPiD#7]
Greetings, I keep running into an issue with ref_seq_gb. I'm working with potential viral regions, and using the All_virus blast db as is (No additional sequences added), have you ran into this particular issue before?
---------------------------------------------------------------------------------------------------------------------------------
Searching local blast database at all_virus.fasta
Warning: [blastn] Examining 5 or more matches is recommended
Traceback (most recent call last):
  File "vapid.py", line 965, in <module>
    meta_list[x], coverage_list[x], sbt_file_loc, full_name_list[x],nuc_acid_type)
  File "vapid.py", line 630, in annotate_a_virus
    name_of_virus, our_seq, ref_seq, ref_accession, need_to_rc = blast_n_stuff(strain, strain + SLASH + strain + '.fasta')
  File "vapid.py", line 185, in blast_n_stuff
    record = Entrez.read(Entrez.esearch(db='nucleotide', term=ref_seq_gb))
UnboundLocalError: local variable 'ref_seq_gb' referenced before assignment

**Comment by rcs333** [comment]
Hi there! This looks like a problem with the installation at some point. Have you verified that running the example.fasta file works with the local blast database? You need to download this from the releases tab if you haven’t already (you need the .nhr .nsq and .nin files). The second thing to check is that the sequence you are attempting to annotate must be a virus that has been well sequenced and annotated. If you submit sequence data that may or may not be a virus the program could crash in this way in the case that the sequence has no homologous to existing sequences in the database. I’m pretty busy with school right now but it is important to me that my software works for everyone!
